--liquibase formatted sql
--changeset tinkov:5
CREATE TABLE user_dog
(
    id            BIGINT generated by default as identity primary key,
    "name"        VARCHAR(30) NOT NULL,
    year_of_birth INTEGER     NOT NULL,
    phone         VARCHAR(20) NOT NULL,
    mail          VARCHAR(20) NOT NULL,
    address       VARCHAR(60) NOT NULL,
    chat_id       BIGINT      NOT NULL,
    dog_id        BIGINT      NOT NULL,
    cat_id        BIGINT      NOT NULL,
    status        INT         NOT NULL
--     FOREIGN KEY (id) REFERENCES reportData (person_id)
);