--liquibase formatted sql

--changeset tinkov:1
CREATE TABLE pet
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    which_pet        TEXT    NOT NULL,
    nickname         TEXT    NOT NULL,
    availability_pet BOOLEAN NOT NULL
);

CREATE TABLE volunteer
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    volunteer_name TEXT    NOT NULL,
    chat_id        BIGINT  NOT NULL,
    available      BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS user_pet
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_chat_id BIGINT NOT NULL UNIQUE,
    full_name    TEXT   NOT NULL,
    contacts     TEXT   NOT NULL
);

CREATE TABLE IF NOT EXISTS trial_period
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date   DATE   NOT NULL,
    end_date     DATE   NOT NULL,
    pet_id       BIGINT NOT NULL REFERENCES pet (id),
    volunteer_id BIGINT NOT NULL REFERENCES volunteer (id),
    user_id      BIGINT NOT NULL
);

CREATE TABLE report
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_date  DATE   NOT NULL,
    photo        TEXT   NOT NULL,
    diet         TEXT   NOT NULL,
    health_status TEXT   NOT NULL,
    behaviour    TEXT   NOT NULL,
    user_id      BIGINT NOT NULL REFERENCES user_pet (id)
);