--liquibase formatted sql
--changeset tinkov:1
CREATE TABLE report_data
(
    id          BIGINT generated by default as identity primary key,
    chat_id     INTEGER             NOT NULL,
    ration      VARCHAR             NOT NULL,
    health      VARCHAR             NOT NULL,
    habits      VARCHAR             NOT NULL,
    filePath    VARCHAR             NOT NULL,
    days        INTEGER             NOT NULL,
    person_id   BIGINT             NOT NULL,
    caption     VARCHAR             NOT NULL,
    lastMessage DATE                NOT NULL,
    data        bytea               NOT NULL
);

-- --changeset tinkov:2
-- CREATE TABLE user_dog
-- (
--     id            BIGINT generated by default as identity primary key,
--     "name"        VARCHAR(30) NOT NULL,
--     year_of_birth INTEGER     NOT NULL,
--     phone         VARCHAR(20) NOT NULL,
--     mail          VARCHAR(20) NOT NULL,
--     address       VARCHAR(60) NOT NULL,
--     chat_id       BIGINT     NOT NULL,
--     dog_id        BIGINT     NOT NULL,
--     cat_id        BIGINT     NOT NULL,
--     status        VARCHAR(30) NOT NULL,
-- --     FOREIGN KEY (id) REFERENCES reportData (person_id)
-- );

-- CREATE TABLE userCat
-- (
--     id            BIGINT generated by default as identity primary key,
--     "name"        VARCHAR(30)         NOT NULL,
--     year_of_birth INTEGER             NOT NULL,
--     phone         VARCHAR             NOT NULL,
--     mail          VARCHAR             NOT NULL,
--     address       VARCHAR             NOT NULL,
--     chat_id       INTEGER             NOT NULL,
--     dog_id        INTEGER             NOT NULL,
--     cat_id        INTEGER             NOT NULL,
--     status        VARCHAR(30)         NOT NULL,
-- --     FOREIGN KEY (id) REFERENCES reportData (person_id)
-- );
-- CREATE TABLE dog
-- (
--     id            BIGINT generated by default as identity primary key,
--     breed         VARCHAR             NOT NULL,
--     "name"        VARCHAR             NOT NULL,
--     year_of_birth INTEGER             NOT NULL,
--     description   VARCHAR,
--     FOREIGN KEY (id) REFERENCES userDog (dog_id)
-- );
-- CREATE TABLE cat
-- (
--     id            BIGINT generated by default as identity primary key,
--     breed         VARCHAR             NOT NULL,
--     "name"        VARCHAR             NOT NULL,
--     year_of_birth INTEGER             NOT NULL,
--     description   VARCHAR,
--     FOREIGN KEY (id) REFERENCES userCat (cat_id)
-- );
-- CREATE TABLE reportData
-- (
--     id          INTEGER PRIMARY KEY NOT NULL,
--     chat_id     INTEGER             NOT NULL,
--     ration      VARCHAR             NOT NULL,
--     health      VARCHAR             NOT NULL,
--     habits      VARCHAR             NOT NULL,
--     filePath    VARCHAR             NOT NULL,
--     days        INTEGER             NOT NULL,
--     person_id   INTEGER             NOT NULL,
--     caption     VARCHAR             NOT NULL,
--     lastMessage DATE                NOT NULL,
--     data        bytea               NOT NULL
-- );
